apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "db.tidb.fullname" . }}"
  labels:
    app: "{{ template "db.tidb.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.tidb.replicaCount }}

  template:
    metadata:
      labels:
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
        app: {{ template "tidb.fullname" . }}
        component: "{{ template "db.tidb.fullname" . }}"

    spec:
      containers:
      - name: tidb
        image: "{{ .Values.tidb.image }}"
        imagePullPolicy: {{ .Values.tidb.imagePullPolicy | quote }}
        ports:
          - containerPort: {{ .Values.tidb.service.mysql }}
          - containerPort: {{ .Values.tidb.service.status }}
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

        command:
        - "/bin/sh"
        - "-ecx"
        - |
          /tidb-server \
          --store=tikv \
          --path="{{ template "tidb.fullname" . }}-pd:{{ .Values.pd.service.ClientPort }}" \
          --metrics-addr=prometheus-pushgateway.default.svc:9091 \
          --metrics-interval=14

        resources:
{{ toYaml .Values.tidb.resources | indent 10 }}

